server:
  port: 8081

spring:
  file:
    upload-dir: static/uploads/
    avatar-dir: avatar/

  datasource:
    url: jdbc:mysql://localhost:3306/webboot?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: sc20041128
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 5MB

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  mybatis:
    mapper-locations: classpath*:mapper/*.xml
    type-aliases-package: org.example.webboot.entity
    configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  web:
    resources:
      static-locations: classpath:/static/

jwt:
  secret: webboot-secret-key
  expiration: 86400000 # 24 hours
  token-header: Authorization
  token-prefix: "Bearer "

file:
  upload-dir: static/uploads/
  avatar-dir: avatar/

app:
  upload:
    dir: ${user.dir}/uploads # 使用项目根目录下的uploads文件夹

logging:
  level:
    org.example.webboot: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

debug: true
